-- Demo headshots for seeded employees (idempotent; only fills empty photo_url on demo accounts)
UPDATE employees SET photo_url='https://randomuser.me/api/portraits/men/32.jpg' WHERE first_name='Arjun' AND last_name='Mehta' AND (photo_url IS NULL OR photo_url='') AND user_id IN (SELECT id FROM users WHERE email LIKE '%@dayflow.local');
UPDATE employees SET photo_url='https://randomuser.me/api/portraits/women/44.jpg' WHERE first_name='Priya' AND last_name='Sharma' AND (photo_url IS NULL OR photo_url='') AND user_id IN (SELECT id FROM users WHERE email LIKE '%@dayflow.local');
UPDATE employees SET photo_url='https://randomuser.me/api/portraits/men/75.jpg' WHERE first_name='Vikram' AND last_name='Singh' AND (photo_url IS NULL OR photo_url='') AND user_id IN (SELECT id FROM users WHERE email LIKE '%@dayflow.local');
UPDATE employees SET photo_url='https://randomuser.me/api/portraits/men/11.jpg' WHERE first_name='John' AND last_name='Doe' AND (photo_url IS NULL OR photo_url='') AND user_id IN (SELECT id FROM users WHERE email LIKE '%@dayflow.local');
UPDATE employees SET photo_url='https://randomuser.me/api/portraits/women/65.jpg' WHERE first_name='Aisha' AND last_name='Khan' AND (photo_url IS NULL OR photo_url='') AND user_id IN (SELECT id FROM users WHERE email LIKE '%@dayflow.local');
UPDATE employees SET photo_url='https://randomuser.me/api/portraits/men/46.jpg' WHERE first_name='Rohan' AND last_name='Patel' AND (photo_url IS NULL OR photo_url='') AND user_id IN (SELECT id FROM users WHERE email LIKE '%@dayflow.local');
UPDATE employees SET photo_url='https://randomuser.me/api/portraits/women/21.jpg' WHERE first_name='Neha' AND last_name='Gupta' AND (photo_url IS NULL OR photo_url='') AND user_id IN (SELECT id FROM users WHERE email LIKE '%@dayflow.local');
UPDATE employees SET photo_url='https://randomuser.me/api/portraits/men/22.jpg' WHERE first_name='Karan' AND last_name='Malhotra' AND (photo_url IS NULL OR photo_url='') AND user_id IN (SELECT id FROM users WHERE email LIKE '%@dayflow.local');
UPDATE employees SET photo_url='https://randomuser.me/api/portraits/women/57.jpg' WHERE first_name='Sneha' AND last_name='Reddy' AND (photo_url IS NULL OR photo_url='') AND user_id IN (SELECT id FROM users WHERE email LIKE '%@dayflow.local');
UPDATE employees SET photo_url='https://randomuser.me/api/portraits/men/85.jpg' WHERE first_name='Amit' AND last_name='Verma' AND (photo_url IS NULL OR photo_url='') AND user_id IN (SELECT id FROM users WHERE email LIKE '%@dayflow.local');
UPDATE employees SET photo_url='https://randomuser.me/api/portraits/women/33.jpg' WHERE first_name='Divya' AND last_name='Nair' AND (photo_url IS NULL OR photo_url='') AND user_id IN (SELECT id FROM users WHERE email LIKE '%@dayflow.local');
UPDATE employees SET photo_url='https://randomuser.me/api/portraits/men/54.jpg' WHERE first_name='Siddharth' AND last_name='Joshi' AND (photo_url IS NULL OR photo_url='') AND user_id IN (SELECT id FROM users WHERE email LIKE '%@dayflow.local');
UPDATE employees SET photo_url='https://randomuser.me/api/portraits/women/12.jpg' WHERE first_name='Pooja' AND last_name='Desai' AND (photo_url IS NULL OR photo_url='') AND user_id IN (SELECT id FROM users WHERE email LIKE '%@dayflow.local');
